[package]
name = "crosswebx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.*"
pollster = "0.3.*"
wgpu = "0.16.*"
winit = "0.28.*"
